/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import 'st-img';


import {
  UsersPage as UsersPage
} from './components/users-page/users-page';

declare global {
  interface HTMLUsersPageElement extends UsersPage, HTMLElement {
  }
  var HTMLUsersPageElement: {
    prototype: HTMLUsersPageElement;
    new (): HTMLUsersPageElement;
  };
  interface HTMLElementTagNameMap {
    "users-page": HTMLUsersPageElement;
  }
  interface ElementTagNameMap {
    "users-page": HTMLUsersPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "users-page": JSXElements.UsersPageAttributes;
    }
  }
  namespace JSXElements {
    export interface UsersPageAttributes extends HTMLAttributes {
      
    }
  }
}

