/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import 'st-img';

import {
  Bar,
  Beer,
} from './global/interfaces';

import {
  barList as BarList
} from './components/bar-list/bar-list';

declare global {
  interface HTMLBarListElement extends BarList, HTMLElement {
  }
  var HTMLBarListElement: {
    prototype: HTMLBarListElement;
    new (): HTMLBarListElement;
  };
  interface HTMLElementTagNameMap {
    "bar-list": HTMLBarListElement;
  }
  interface ElementTagNameMap {
    "bar-list": HTMLBarListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "bar-list": JSXElements.BarListAttributes;
    }
  }
  namespace JSXElements {
    export interface BarListAttributes extends HTMLAttributes {
      bars?: Array<Bar>;
    }
  }
}


import {
  BeerItem as BeerItem
} from './components/beer-item/beer-item';

declare global {
  interface HTMLBeerItemElement extends BeerItem, HTMLElement {
  }
  var HTMLBeerItemElement: {
    prototype: HTMLBeerItemElement;
    new (): HTMLBeerItemElement;
  };
  interface HTMLElementTagNameMap {
    "beer-item": HTMLBeerItemElement;
  }
  interface ElementTagNameMap {
    "beer-item": HTMLBeerItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "beer-item": JSXElements.BeerItemAttributes;
    }
  }
  namespace JSXElements {
    export interface BeerItemAttributes extends HTMLAttributes {
      beer?: Beer;
      fave?: Boolean;
    }
  }
}

